In [1]:
import tensorflow as tf

In [2]:
message = tf.constant('Welcome to the exciting world of Deep Neural Networks!')
with tf.Session() as sess:
    print(sess.run(message).decode()) 


Welcome to the exciting world of Deep Neural Networks!


In [3]:
v_1 = tf.constant([1,2,3,4])
v_2 = tf.constant([2,1,5,3])
v_add = tf.add(v_1,v_2)
with tf.Session() as sess:
    print(sess.run(v_add)) 

[3 3 8 7]


In [4]:
#The above two commands are equivalent to the following code. The advantage of using with block is that one need not close the session explicitly.
v_1 = tf.constant([1,2,3,4])
v_2 = tf.constant([2,1,5,3])
v_add = tf.add(v_1,v_2)
sess = tf.Session() 
print(sess.run(v_add)) 
sess.close() 

[3 3 8 7]


In [5]:
#in 1 line
print(tf.Session().run(tf.add(tf.constant([1,2,3,4]),tf.constant([2,1,5,3]) ))) 

[3 3 8 7]


In [6]:
#If you are working on Jupyter Notebook or Python shell, it is more convenient to use tf.InteractiveSession instead of tf.Session. InteractiveSession makes itself the default session so that you can directly call run the tensor Object using eval() without explicitly calling the session, as described in the following example code:

sess = tf.InteractiveSession()
v_1 = tf.constant([1,2,3,4])
v_2 = tf.constant([2,1,5,3])
v_add = tf.add(v_1,v_2)
print(v_add.eval())
sess.close()


[3 3 8 7]


In [7]:
t_1 = tf.constant(4)

#A constant vector of shape [1,3] can be declared as follows
t_2 = tf.constant([4, 3, 2])

#To create a tensor with all elements zero, we use tf.zeros(). This statement3. creates a zero matrix of shape [M,N] with dtype (int32, float32, and so on):
zero_t = tf.zeros([2,3],tf.int32) 

#We can also create tensor constants of the same shape as an existing Numpy4. array or tensor constant as follows:
tf.zeros_like(t_2)
# Created a zero matrix of same shape as t_2 , (similarly tf.ones_like(t_2))


<tf.Tensor 'zeros_like:0' shape=(3,) dtype=int32>

In [8]:
range_t = tf.linspace(2.0,5.0,5)
# We get: [ 2.    2.75  3.5   4.25  5.  ] 

range_t = tf.range(10)
#(default=0), incremented4. by delta (default =1)

In [9]:
#To create random values from a normal distribution of shape [M,N] with the1. mean (default =0.0) and standard deviation (default=1.0) with seed, we can use the following:
t_random = tf.random_normal([2,3], mean=2.0, stddev=4, seed=12)
# Result: [[ 0.25347459  5.37990952  1.95276058], [-1.53760314 1.2588985   2.84780669]]

#To create random values from a truncated normal distribution of shape2. [M,N] with the mean (default =0.0) and standard deviation (default=1.0) with seed, we can use the following:
t_random = tf.truncated_normal([1,5], stddev=2, seed=12)
# Result: [[-0.8732627 1.68995488 -0.02361972 -1.76880157 -3.87749004]] 

In [10]:
# To create random values from a given gamma distribution of shape [M,N] in the range [minval (default=0), maxval] with seed, perform as follows:
t_random = tf.random_uniform([2,3], maxval=4, seed=12)
# Result: [[ 2.54461002  3.69636583  2.70510912], [ 2.00850058 3.84459829  3.54268885]] 

In [11]:
tf.random_crop(t_random, [2,5],seed=12) 
tf.random_shuffle(t_random)
tf.set_random_seed(54) 

In [12]:
rand_t = tf.random_uniform([50,50], 0, 10, seed=0)
t_a = tf.Variable(rand_t)
t_b = tf.Variable(rand_t) 
#Variables are often used to represent weights and biases in a neural network.


In [13]:
weights = tf.Variable(tf.random_normal([100,100],stddev=2))
weight2=tf.Variable(weights.initialized_value(), name='w2') 

In [14]:
#Each variable can also be initialized separately using5. tf.Variable.initializer during the running graph:

intial_op = tf.global_variables_initializer()
bias = tf.Variable(tf.zeros([100,100]))
with tf.Session() as sess:
    sess.run(bias.initializer)

In [15]:
saver = tf.train.Saver() 

## PLACEHOLDER

In [16]:
#placeholders, they are used to feed data to the graph. 
#. Here, we define a placeholder for x and calculate y = 2 * x using feed_dict for a random 4×5 matrix:

x = tf.placeholder("float")
y = 2 * x
data = tf.random_uniform([4,5],10) 
with tf.Session() as sess:    
    x_data = sess.run(data)  
    print(sess.run(y, feed_dict = {x:x_data}))


[[ 4.3502655 14.418005  19.649063  18.77413   13.136597 ]
 [ 2.2432823  3.3825378 17.670773   8.047263  16.958218 ]
 [ 4.358715  11.3488865 10.752256  10.332763  13.038402 ]
 [17.571424  18.672045  16.945824   6.8418875  4.264269 ]]


In [17]:
import tensorflow as tf
#Start an Interactive Session
sess = tf.InteractiveSession()
#Define a 5x5 Identity matrix 
I_matrix =tf.eye(5) 
print(I_matrix.eval()) 
# This will print a 5x5 Identity matrix
#Define a Variable initialized to a 10x10 identity matrix 
X = tf.Variable(tf.eye(10))
X.initializer.run() 
# Initialize the Variable
print(X.eval())
# Evaluate the Variable and print the result
#Create a random 5x10 matrix 
A = tf.Variable(tf.random_normal([5,10]))
A.initializer.run()
#Multiply two matrices
product = tf.matmul(A, X)
print(product.eval())
#create a random matrix of 1s and 0s, size 5x10
b = tf.Variable(tf.random_uniform([5,10], 0, 2, dtype= tf.int32))
b.initializer.run()

print(b.eval())
b_new = tf.cast(b, dtype=tf.float32)
#Cast to float32 data type
# Add the two matrice
t_sum = tf.add(product, b_new)
t_sub = product - b_new
print("A*X _b\n", t_sum.eval()) 
print("A*X - b\n", t_sub.eval()) 
sess.close()

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[-1.3359236   0.764569    0.2856698  -0.253296   -1.6790226   0.5317206
  -0.9466202   0.25567088 -1.9711678   0.24675463]
 [ 0.22885749  0.23673335 -2.047524    0.41429302  1.4742044  -0.4852729
  -0.69237554 -0.4336081  -0.25084692 -0.811446  ]
 [ 0.31752962  0.20787452 -0.2221204  -0.2187315   0.8708996   0.24889998
  -0.7643637  -1.4146484   0.962386   -0.99511015]
 [-0.6579213  -0.3127666  -0.5968802  -0.7470046  -1.1117313  -1.2939056
   0.04836388  0.86316514  1.4066361   2.306386  ]
 [ 1.4565439  -0.63394773 -0.6181454  -1.6682159  -0.91090685  2.463484
   0.8905

In [47]:
bias = tf.Variable(tf.zeros([10,10]))
A = tf.Variable(tf.random_normal([10,10]))
weights = tf.Variable(tf.random_normal([10,10],stddev=2))

with tf.Session() as sess:
    sess.run(bias.initializer)
    sess.run(A.initializer)
    sess.run(weights.initializer)

    merged = tf.summary.merge_all()
    tf.summary.scalar('loss', bias) 
    # Initialize the Variable
    #You can also visualize the distribution of gradients, weights, or even output of a2. particular layer using tf.summary.histogram:
    output_tensor  = tf.matmul(A, weights) + bias

    tf.summary.histogram('output', output_tensor)

    #The generated summary then needs to be written in an event file using4. tf.summary.Filewriter
    #writer = tf.summary.Filewriter('summary_dir', sess.graph)
    train_writer = tf.summary.FileWriter('summary_dir' + '/train',sess.graph)
    
    
   # tensorboard --logdir='summary_dir'
    #this line gives error 




SyntaxError: can't assign to operator (<ipython-input-47-2b2e434d21da>, line 23)